### ISSUE TITLE
Allow for global gradle options

### ISSUE THREAD

**Issue by wvreeven** [kelemen/netbeans-gradle-project#113]
When I am testing and debugging my code, I'd like the --info option to be used to show all log output. At the moment I need to add the --info option manually for each project in NetBeans. Please allow for a global preference that adds this (and possibly other) gradle option, e.g. below the "Always clear output window" option.

**Comment by swltr** [comment]
It would also be great to have a checkbox for globally setting '--offline', so you don't have to do it in the projects' settings. (I'm aware that this issue is about global options in general. I just wanted to express interest in this particular checkbox.;-)

**Comment by hrstoyanov** [comment]
I also need the --offline option setable at global Netbeans level, just like the gradle home (-g) already there. When can we get this?

**Comment by kelemen** [comment]
@hrstoyanov I'll probably add features like this on the weekend after doing some cleanup.

**Comment by hrstoyanov** [comment]
Eagerly expecting your next release! Thank you for the awesome plugin BTW!!

/Hristo Stoyanov

**Comment by kelemen** [comment]
This should be fixed in master. As for when I'll have the next release, I'm not sure. As the minimum, I'd like to allow customizable project display name and maybe a few minor things. Until then, you can build the plugin from the sources (read the [Development page](https://github.com/kelemen/netbeans-gradle-project/wiki/Development), if you need any help with that).

**Comment by swltr** [comment]
Thank you, Attila!
