### ISSUE TITLE
"Stop" debug toolbar button doesn't stop the running process

### ISSUE THREAD

**Issue by ninjabear** [kelemen/netbeans-gradle-project#158]
Normal behaviour in netbeans is that when you "stop" the debug it kills the running process. This is handy because runaway processes can be killed from netbeans. 

The issue also occurs when you run the process, and go to "stop build/run" - the process isn't stopped. 

I'm using netbeans 8.0.1 and gradle 2.1 (though the issue also occurs with the gradle wrapper, not sure what version that is on now)

**Comment by AMetnik** [comment]
I have this problem, with the current version 1.3.7.3.

It's a gradle project, running spring boot (utilizes an embedded tomcat). When trying to click the [x] to shut down process, it does nothing.
It's on netbeans 8.0.2, and spring-boot version: 1.0.2.RELEASE.
I've earlier tested with other projects, all seems to not cancel the run operation.(then i switched to run them in eclipse since that is what rest of dev. team uses)

![skaermbillede 2015-10-15 11 36 38](https://cloud.githubusercontent.com/assets/2640098/10509955/7945d4f0-7330-11e5-9477-4ad9f0161c31.png)

**Comment by kelemen** [comment]
Which version of Gradle are you using? You need to use Gradle 2.1 or newer for this to work (also, stopping does not happen instantly but after a few seconds).

**Comment by AMetnik** [comment]
@kelemen Thanks that was exactly my problem
