### ISSUE TITLE
Working directory is Netbeans/bin directory and not project directory

### ISSUE THREAD

**Issue by avanderw** [kelemen/netbeans-gradle-project#159]
By default running the gradle jettyRun from the plugin executes from the Netbeans/bin directory and not the project directory. 

This means that relative pathing is not working correctly. e.g.
**System.out.println(new File("").getAbsolutePath())**
- gives "C:\Program Files\NetBeans 8.0\bin"
- instead of "C:\Projects\MockServices"

*Running from command line works correctly.*

## Console output ##
Executing: gradle jettyRun

Build file 'C:\E-Channels\Source\Bancs Connect\build.gradle': line 289
The TaskContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.
**C:\Program Files\NetBeans 8.0\bin**
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:ProjectA:compileJava
:ProjectA:processResources UP-TO-DATE
:ProjectA:classes
...
*jettyRun fails to load project due to incorrect resolving of paths (jetty is booted, though)*

**Comment by kelemen** [comment]
**For everyone having this issue**, this is what you can do (it is impossible for me to fix):

- Fix your build script not to rely on the working directory. This is the preferred solution and in my opinion the only correct one.
- Pass "-Duser.dir=my-working-directory" JVM argument, you may set this in the global setting. This will be constant for all projects though.

**Comment by aplatypus** [comment]
@kelemen ... This is not a solution.

In the simplest case Netbeans can `exec( "gradle build" )` as a command in the project's directory.  Specifically the project directory is the place where the parent `build.gradle` file lives.

Netbeans supports 4 build systems that I know about ...

1.  Java Ant
1. Maven builds
1. C/C++ makefile builds
1. Gradle builds

At thie time Gradle plugin is the ONLY project builder that doesn't start the build in the project directory.  A great many projects and all the Netbeans generated Ant projects all use relative directory paths relative to the **project directory**.

Netbeans is in Java -- yet all the three working build tools manage to run project builds form the project directory.  

Concerning the hack of setting the `-Duser.dir=my-working-directory` -- How do you do that!?  Only Netbeans has the context of where the build file is loaded from.   Is there an Environment variable that Netbeans sets to provid that location?  The project path is meta-data outside the Gradle ken.

Alternatively, is there some Gradle property on the project file that gives the file path to that file at Gradle run-time?

Factually the only entity that know where a grade `build.gradle` file is in the first instance is the application that kicks it off.  When I begin a Gradle build from the command line that is the only time  you know where the project is.  Under some scenarios I may have 3 or 4 versions of a project check-out for work.  One or two different older versions for bug fixes, current development trunk and perhaps two or more feature branches.

These are different folders and yet ostensibly they are the SAME project -- Just different versions.

**Comment by aplatypus** [comment]
Hi all.

I have a robust _hack_ for this situation.  Gradle knows where the build script lives
- (Gradle) [Project properties](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#N1443F)

Setting the Java directory to the location for the project

```
    println  "Root project:   "+ project.rootProject;
    println  "  rootDir:      "+ project.rootDir;
    println  "  projectDir:   "+ project.projectDir;
    println  "  project dir:  "+ System.getProperty("user.dir");

    System.setProperty( "user.dir", project.projectDir.toString() );    <-- try this
    println  "  project dir:  "+ System.getProperty("user.dir");
    println  "";
```

**Comment by kelemen** [comment]
Please read my answer in #326.

**Comment by aplatypus** [comment]
Thank you for responding.  I have pointed #326 here for further comments as this appears to be the core issue.  As I said for 326 I do not agree with the response.   I believe there is a mismatch in current performance and Gradle documentation, see below.

Looking over the Gradle v3.4.1 documents today, every mention of folders, files and projects documents them as "_relative to the project directory_"
- https://docs.gradle.org/current/dsl/org.gradle.api.Project.html
 
Furthermore the section on "**Working with Files**" repeats this information:
- https://docs.gradle.org/current/userguide/working_with_files.html

And while "_Yes_." Gradle has methods to ensure a file is loaded in context; not no Java, Ant, Groovy and not every Gradle snippet is/will be written to run in that context.  I saw for example the same question asked on Stackoverflow how to set the right directory for an Ant plugin.

The need, at the end of the day, is for mechanics that get the job done.  It is illogical for a build script to have two different instances of the "**current working directory**".

**Comment by aplatypus** [comment]
A follow-up from #326 ...

Also to clear-up a minor point.  I checked an old Maven build under Netbeans  The first line of the Maven launcher -- Netbeans Maven plugin sets the current directory and other build parameters needed.

> cd D:\work\products\apps\lib\tmacs\java7; 
> JAVA_HOME=...
> M2_HOME=
> -DskipTests=true 
> -Dmaven.ext.class.path= ...
> -Dfile.encoding=UTF-8 install\""

It is not Netbeans, these values are established by the plugin prior to starting the Maven command.

I cannot think of, a build system where it makes a lot of sense or does much good to have a "build script" run in a Different directory.  

That said; it **_ought_** to be possible for the Gradle plugin to have an option to change to Set the Current Working Directory to the Project Directory.  Then people with projects that work that way can be happy and not be forced to run scripts from the command line (just like we did the the 70-s).

**Comment by kelemen** [comment]
Despite what you believe, it is **not possible** for the plugin to set the working directory for your build. If you really-really want to, you can ask Gradleware to change `GradleConnector` to set the working directory to the project directory (or allow it to be configured). Though, even if they changed this behaviour, I would still highly recommend you not to rely on that. There are quite a few thing which can go wrong, if you just keep carelessly relying on the working directory. For example, it will not be possible to run your script concurrently with another one within a single process. Also, it is not even obvious which project directory (assuming a multi-project build) are we talking about.

I don't understand your problem with Gradle's API. They work as advertised, as far as I know.

Also, you have said: "at the end of the day, is for mechanics that get the job done". Well, there is a lot of mechnics, just none of them involves the use the working directory. You don't have to rely on the command line, you just have to fix the build script. Not using the current working directory is the right thing to do (tm) anyway. I have serious doubt, that you will find any at least half decent library which will force you to use the working directory.

It is not that it makes sense or not, it is just not possible. There is no reason to compare it to Ant or Maven. The main difference is that the plugin never really literally issues a Gradle command. What is printed in the output window is just printed for informational purposes. That is, the plugin does not start a new "gradle" process when you run a task. It just talks with a daemon process running in the background via TCP/IP (if there is no daemon, it starts one and will keep using that daemon if it can). This actually speeds up build script parsing by a *lot*.

**Comment by aplatypus** [comment]
Hello ... there is no confusion.  The Gradle DSL specifies that the main **project directory** is-the **`project.rootDir`** which is (_always_) the value of the **`project.projectDir`** when the current project is the root project.

In another thread I saw a recommendation to use a project properties dialogue setting ...
- -Duser.dir=<_pathString_>

That can be done as suggested and in the script the system call does the same thing:
- `System.setProperty( "user.dir", "`_pathString_`" )`

We will have to agree to not agree.  It is equally Not Possible to run or use anything that needs a relative file path name if the actual current working directory is unpredictible.

**Comment by swpalmer** [comment]
If you are running a command from a gradle build script you can specify what the working directory for the launched process is.

**Comment by kelemen** [comment]
I don't know where you got that it is the "main" and what do you want to imply with "main". If you think that it is obvious, you are not exactly consistent with the command line. If you run Gradle from the command line, the working directory is from whatever directory you are starting Gradle. It does not have to be the root project, as you might want to run Gradle from a directory of a subproject, if you want to run something for only a subtree of the whole project tree. Not to mention that even if your project worked from NB, it would still break in Eclipse. Do you really think it is worth to always be afraid which tool will fail to understand your build script?

Also, earlier you mentioned "there is a diffence in semantics between Netbeans and the Gradle documents". I don't see how this could be the case. The Gradle API does what it says it does, there is no way NB affecting it.

That said, can you tell me even a single example where it is not possible (or just not reasonably feasible) to avoid relying on the working directory? I have honestly never seen such an issue in my life. As for your scripts linked earlier: They are trivial to fix (2 lines change and your script would even be smaller by a few chars), and I consider them broken.

**Comment by aplatypus** [comment]
Hello.  I believe my IDE, e.g. Netbeans should execute a (Gradle) build '**as-if**' or in fact, with the same context as the same build command issued from the command line.  And that is a _necessary_ consistency because IDE builds are only conveniences.  The production builds, tests and other builds are executed by scripts or build servers.

With systems like:
- make
- Maven
- Ivy
- Gradle

When I issue a build command I picks up a project build file in the current working directory as the default behaviour.
- make looks for  `./makefile'
- Maven looks for 'pom.xml`
- Gradle looks for `build.gradle`

So the "_normal_" working directory for a (Gradle) build ought to be the location of the project file.
- makefile for make
- pom.xml for Maven
- build.gradle for Gradle

And this is written into the Gradle documentation as cited earlier.  The Gradle v3.4.1 documents today, every mention of folders, files and projects documents them as "relative to the project directory"

- https://docs.gradle.org/current/dsl/org.gradle.api.Project.html

Furthermore the section on "Working with Files" repeats this information:

- https://docs.gradle.org/current/userguide/working_with_files.html

Referring to the command line again.   If I `cd` to the  Netbeans user directory, let's call it netbeans/user...
 then nothing happens when I try to run Gradle because there is no `build.gradle` file there.
```
 cd ~/netbeans/user
 gradle build
:buildEnvironment
------------------------------------------------------------
Root project
------------------------------------------------------------
classpath
No dependencies
BUILD SUCCESSFUL
Total time: 2.409 secs
```

And YET the Netbeans Gradle plugin seems (sometimes) to start builds in the Netbeans User directory.  Sometimes it will not, it will begin a build from what ever directory the Netbeans GUI was started from.

As a consequence the root gradle.build file at least is looking for files in the wrong location.

Imho, the plugin should begin gradle tasks with the `-p` option:
```
   -p, --project-dir       Specifies the start directory for Gradle. Defaults to current directory.
```
and thus ensure that ALL builds begin in the location of the `./build.gradle` script being executed.  Just the same manner as happens from the command line in that projects build directory.

This is how all build systems work, including gradle, and most of the IDE support of the  various build tools start builds in the project's directory.   I personally and on our projects, we do not want to have to take special action with IDE builds.  What the IDE does must be the same as what happens on the command line.  

I also think that's what most people _Expect_ to happen.  There were enough stackoverflow and questions already asking about this when I started looking to convince me that people want it that way.  For me I just know I like writing LESS code just to build something with a consistent process.

**Comment by kelemen** [comment]
The fact that the working directory is the project directory, when you are running gradle from the command line, is mere coincidence. This simply happens because it is more convenient to run gradle from the directory of the project. This is not necessary though, you could run your build task this way from any directory: `gradle -c /mypath/settings.gradle -p /mypath/subprojectdir build` and correct build script would do the same thing (regardless from where you started gradle). If the build does not do the same, then the build script is wrong (buggy so to say).

The reason why this is more apparent in Gradle is mostly due to builds run by a shared daemon. Also, since you are directly writing code, nothing can stop you from writing a code which uses the working directory. You have chosen to do so, something which you should change, because it is generally not a good practice to rely on the working directory. The working directory is simply a way for a human user to provide input for a particular executable on start. However, you don't need this and it doesn't even make the build script harder to write. I wrote quite a lot of Gradle builds and have never had any issue when relying on the working directory (assuming it was say the root project directory) would make things easier. In fact, the code is pretty much always simplier if you do not rely on that. The only thing you have to do is to pass around `File` (or `Path`) objects instead of `String` and everything becomes trivial (this is the same with scripts you have linked earlier).

What you have linked in the Gradle documentation have nothing to do with what you are saying. They are APIs there and many of them choose to interpret their properties relative to the project directory (given that they are not absolute paths). This does not support you because they do not say that they rely on the working directory (simply because relying on it would be wrong). So, the use of those APIs are unaffected by the current working directory. This by no means imply anything about the location of the current working directory. The  same is with the "Working with Files" section. They do not reference (for good reason) the current working directory. For you reference, here is a quote from that section:

> Using this method is a useful way to convert some user provided value into an absolute File. It is preferable to using new File(somePath), as file() always evaluates the supplied path relative to the project directory, which is fixed, rather than the current working directory, which can change depending on how the user runs Gradle.

As you can say, they explicitly say that location current working directory is undefined for the build script.

The "-p" argument doesn't do what you claim it does. I would rather not elaborate on what it does but for your information: The plugin effectively already sets that.

And again: **It is impossible for me to set the working directory without causing other potential (worse than your) problems.** If there was one without negative side effects, I would have done it because why not. However, if you think I have missed something, and you know a way, then tell me the solution. I don't know any and fairly certain that I know the possibilities.

You don't need to take special actions for the IDE. You just have to make your build scripts independent of the working directory. This has nothing to do with the IDE, this is simply writing the build scripts properly (and not making its behaviour undefined). Gradle nowhere defines that the working directory is somehow related to the project directory. You can try finding such definition but you won't find any. That is, relying on the working directory makes the behaviour of your build scripts undefined.

Admittedly, there are people whose first instinct is to rely on the working directory. However, I'm fairly certain that vast majority does not do so (as there is no need) and others (mostly) realize later that it is the wrong thing to do. Therefore, I advise you the fix this bug in your build scripts. Otherwise, you will run into this issue with the majority of tools making use of the Tooling API of Gradle.

**Comment by JustGregory** [comment]
I believe Attila Kelemen is correct in everything said above; this is how I have always thought of it, but I am very glad that it was explained better than I ever could.

p.s. I believe Attila is trying to tell everyone to "STOP OVER-THINKING IT". Or at least, this is what I'm reading (in second-from-last paragraph).

**Comment by mailursubbu** [comment]
Quick work around:

settings.gradle 
/**
* This would explicitly set the root project dir
**/
project(":").projectDir =
          new File (settingsDir, ".")
