### ISSUE TITLE
'Run' the webapp in NetBeans' default installed tomcat?

### ISSUE THREAD

**Issue by chiahao** [kelemen/netbeans-gradle-project#173]
There's similar issue: [Add support for web projects](https://github.com/kelemen/netbeans-gradle-project/issues/42)
, but I don't understand the conclusion.

So can we 'Run' the webapp in NetBeans' default installed tomcat?

Is it possible to just right click on the project, and select 'Run' to run the project just like that NetBeans Web Application runs in NetBeans' tomcat. 

Thanks for help.

**Comment by kelemen** [comment]
Webapp project related things are to be supported by hildo's plugin: [netbeans-gradle-javaee-project](https://github.com/hildo/netbeans-gradle-javaee-project).

Anyway, when you click "Run", NetBeans will just execute the "run" task (by default). You can create a "run" task in your build script which does what you want (or a task with another name and configure NetBeans "Run" command accordingly in the project's properties).

**Comment by wadechandler** [comment]
I would like to add that I very much appreciate and like the way that the NetBeans gradle support uses the gradle script to perform the actions. This means variables and dependencies I define are used in the IDE. It also means any script which I have customized around the notion of running or testing or debugging my application are also used. This is very important. Various others using a current Gradle project with the Eclipse tools have different issues because of this on my current project.

**Comment by wadechandler** [comment]
If the current support does not inject information related to those services in the NetBeans IDE, then that may very well be a room for improvement. For any known and detectable services and any connection related information the tooling could build specific objects that get injected into the Gradle project. This could allow people to write customized tasks for when running in the environment. This is a middle-of-the-road solution suggestion for both parties.

**Comment by elennaro** [comment]
+1
