### ISSUE TITLE
Dependencies from local Maven cache refreshed only after restarting NetBeans

### ISSUE THREAD

**Issue by swltr** [kelemen/netbeans-gradle-project#186]
For local development/testing, I'm using the Maven plugin's `install` task to deploy artifacts (snapshots) to the local Maven cache, and referencing `mavenLocal()` in another project to use these artifacts as dependencies. It seems that, after installing an artifact to the local Maven cache, even reloading the project in NetBeans does not refresh these dependencies:

1. I add a class `FooBar` to project A.
2. I `install` the resulting artifact to the local Maven repo.
3. I reload project B, which uses project A's artifact and references `mavenLocal()`.
4. I try to use class `FooBar` in project B, but cannot find it - neither via autocompletion, nor in the JAR file displayed in the dependency list.
5. I restart NetBeans, after which class `FooBar` is usable/visible.

This is on NetBeans 8.0.2 and with projects that set `resolutionStrategy.cacheChangingModulesFor 5, 'seconds'` (so the caching timeout should not be the problem).

**Comment by kelemen** [comment]
Dependencies in Maven local are maintained by the Maven plugin in NetBeans. So, I guess the Maven plugin does not listen for changes in the whole "~/.m2/repository" (understandibly). However,I need some info to be sure what could cause this:

1. In what name does Gradle install your artifacts to the repo (it used to append "-<DATETIME>" instead of "-SNAPSHOT", I don't know if Gradle still does the same thing).
2. Does "Source/Scan for External Changes" solve this issue?

**Comment by swltr** [comment]
(Just to avoid misunderstandings: With "Maven plugin", I meant the Maven plugin in Gradle.)

Running Gradle's `install` task just appends `${version}-SNAPSHOT` to the project name in the artifact's file name, e.g. `myproject-0.5-SNAPSHOT.jar`.

Selecting "Scan for External Changes" from the "Source" menu does indeed solve this - thanks for the hint! Running this explicitly I would already consider an acceptable solution - although it would be great to have "Reload Project" implicitly do this, too, given that it usually refreshes dependencies from remote repositories, too.
