### ISSUE TITLE
Should work better with 'application' plugin

### ISSUE THREAD

**Issue by swpalmer** [kelemen/netbeans-gradle-project#187]
The 'application' plugin uses a different property to specify the main class.
The NetBeans plugin should use the same property soi I don't need to tweak the gradle files to work with netbeans;

if (!hasProperty('mainClass')) {
    ext.mainClass = 'com.imaginecommunications.bpmntest.Main'
}
// NB plugin has above lines by default, but...
mainClassName = mainClass // <- must add this line to work with the 'application' plugin

See: http://gradle.org/docs/current/userguide/application_plugin.html

**Comment by kelemen** [comment]
I know of this awkwardness (I didn't know about the application plugin when I implemented this) but I cannot easily change this without breaking backward compatibility. I was thinking of setting both properties but I have mixed feelings. Anyway, you can configure the built-in task (run single) to pass the property you want instead (though you have to do this for every multi-project build).

**Comment by swpalmer** [comment]
Perhaps compatibility can be preserved by automatically checking the same property as the application plugin only if the mainClass property is not set?

Scott

**Comment by altavir** [comment]
Another problem with 'run Single' task. I need to have main class (preferably via application plugin) but also to run some testing groovy scripts. Once I set mainClass property (or us application plugin), any attempt to run selected script via 'run File' tries to ran general main class instead.
For now the only solution is not to use application plugin or ext.mainClass, bu use my own run task instead.

**Comment by kelemen** [comment]
I don't see why you can't use the application plugin. You can use the code Scott showed in the post and that should work for you (that is, only set the `mainClass` property if it is not already set).

**Comment by altavir** [comment]
Tried that, but it seems I am doing something wrong. Let me try to retrace my steps:
* I am turning on application plugin, but do not define `mainClassName`. Nothing works since application overrides `run` task and it does not have main class.
* I am adding the code Scott suggested:
    if (!hasProperty('mainClass')) {
      ext.mainClass = 'my.main.class.Here'
    }
Nothing works still because run task is overridden and ignores `mainClass` property.
* I am adding `mainClassName =  'my.main.class.Here'` to the configuration. `run` task works like charm, bu if I am trying to `run single` on my script, it still starts `my.main.class.Here` since `run single` inherits but does not overrides `run` task for which the main class is already defined

What am i doing wrong?

**Comment by kelemen** [comment]
You are missing the `mainClassName = mainClass` line (after the `if (!hasProperty ...`) code.

**Comment by altavir** [comment]
Oh, missed the last line. Thank you. Works fine now. It would be good to write this trick in the project documentation.

**Comment by kelemen** [comment]
I have added some code to the init script to adjust the application plugin's `mainClassName` property when `mainClass` is specified or set `mainClass` if `mainClassName` is specified but `mainClass` is not.
