### ISSUE TITLE
Cannot pass arguments to main method

### ISSUE THREAD

**Issue by Tanshaydar** [kelemen/netbeans-gradle-project#194]
For my main method I have to give a file path as argument, otherwise I cannot run the the project.
Since I'm tied to the project over git, I am not able to make changes to gradle files.

I have been trying to give file path to run task as argument for the project, but it says it cannot find C in my project.

This had been very easy if the project was to be configurable like a Java project, as in Eclipse I can give the argument to Run options, but I don't want to use Eclipse like rest of the team.

**Comment by kelemen** [comment]
I don't understand your "it says it cannot find C" comment. Anyway, NetBeans just attempts to run the "run" task of your project, unlike Eclipse which does not rely on the build script.

If you cannot edit the build scripts of your project directory, you can do so through init scripts. For example, add something like the following to your "~/.gradle/init.gradle" file:

if (projectDir == new File('absolute-path-to-project')) {
    afterEvaluate {
        // Create run task if necessary, or if there is already one
        // run.args = ['my-arg']
    }
}

You might also want to check "Don't add tasks to build scripts automatically" in the global settings if you are doing something like this. Though, this is not necessary, depending on how you implement your init script.

**Comment by aplatypus** [comment]
I'm also finding specifying command line arguments for the Debug and Run commands a problem.

I really don't follow the instructions to use an init script with gradle.  If we need to do that, we would be using the command line and just run the JAR (more or less).  

In an IDE like NetBeans or IDEA, and VisualStudio (shudder) one expects to use the GUI to set and change project properties, including the command line arguments for the Run and Debug command.   

The Gradle plug-in project and main project properties really don't "add" much.  So far I've needed to edit the necessary .gradle  file to make most things I normally use the NetBeans project properties to achieve.  It is not just a hidden and steep learning curve, it makes Gradle with netbeans incompatible with the normal development workflow among my team mates.

It would be highly desirable if the Gradle user experience mirrored the UI and work processes of the "typical Netbeans Java" project.  An essential place to begin I believe is the access and modification of command line args[] for the Main class with Run and Debug.  Everyone needs to do that.

**Comment by kelemen** [comment]
It might not be trivial to notice but the biggest difference between NetBeans and other IDEs (like IntelliJ) is that NetBeans does not have its own build system. That is, in all project types it delegates tasks to the build system of the project (be it Ant or Maven or whatever). The reason why I can't provide a very convenient way for command line arguments is because "running a project" is not well standardized within Gradle. That said, I could pick a use-case and generate an init script for that use-case. However, then everyone doing project running in a different way would be amazed (and annoyed) to see that something that "should" work does not.

By the way, in the latest version of the plugin, you can specify an init script to be applied for a project in the project properties, so in that init script you don't need the "if" to select the project, you can simply write:

    afterEvaluate {
        // Create run task if necessary, or if there is already one
        // run.args = ['my-arg']
    }

That I believe is a minimal overhead compared to some very specific UI. Though, I understand your concern, that in NetBeans you have to understand Gradle well in order to make something seemingly trivial thing work. However, I believe that the main advantage of NetBeans is that it relies on the build tool comes with the price of not being able to forget about the build tool.

Anyway, if you have a specific idea (exact UI included), how this feature should work: Don't hold back, I'm open to ideas. But keep in mind that in the end NetBeans will always have to refer to the build script to run a project (since as I said before, it does not have its own build system).

**Comment by aplatypus** [comment]
A good UX is never trivial, even when it appears to be simple.

The power of Netbeans and IDEA is that they both don't do their own builds.  I have used both Netbeans and IDEA extensively and both have a UI for either Maven and Ant builds.  The opportunity is for _integration with_ the build not to compete.  I would say Gradle is just another build and I agree there are always choices with a UI.

A counter example is the (lack of) integration for Maven with Eclipse -- I find Maven builds on Eclipse quite cumbersome.  Which surprised me really.  In that light, I'd be emulating the existing UI for project properties and Run argument for Netbeans for Ant (the standard Netbeans project) and Maven projects since they are very close in structure and UI while accepting that nothing is perfect.  As Maven and Gradle have some common ground, it would be good to learn from the UI mistakes delivered with the Netbeans Maven UI.

There must be a way in an IDE to debug (or to run) a project with arguments from UI.  Otherwise it is just a DE (development environment) with script.

**Comment by kelemen** [comment]
Actually, IDEA does its own build, in some sense it does compete/co-exist with the build tool (you just import projects from the Gradle build scripts). You can run Gradle tasks from it but thats a different story. That is, for IDEA, run/debug configuration is a simple matter because it explicitly calls Java with a given classpath. However, in NB you are executing a Gradle command and you do this for every kind of command (run/build/test etc.). So, my question is how do you expect argument passing should work in general? Because I have no idea how it should be done to be backward compatible with current project configurations and yet in a way that works with the majority of use-cases.

I'm not sure about the UI mistakes done in the Maven integration because it was a long time ago since I have used Maven for anything but trivial things. Anyway, there is little to no common grounds between Maven and Gradle especially from the IDE's perspective.

Though, I agree that this might be the largest shortcoming of the NB integration, I don't see a reasonable way to fix this. There might be a way but I don't yet see it, so that's why I asked if you have a good idea, don't hesitate :).

**Comment by joebowbeer** [comment]
Can this be smoothed over by adding some additional templates for NB gradle projects?




I assume the DIY method that everyone employes is to add a bit of script that unpacks a designated -P assignment and assigns it to args[] in the run/debug tasks.




Some additional UI would provide a space to fill-in the value of this -P assignment?



—

**Comment by kelemen** [comment]
@joebowbeer Where would you expect to find such an UI? Also, what benefit such an UI has from the already existing one (configuration of a built-in task)?

By the way, what would you think of something like allowing an init script to be specified for each command (like run/debug)? (though you can already specify an init script for projects)

**Comment by jdevora** [comment]
On the Project properties,  you can modify the "build in tasks" and add extra arguments to pass to gradle, but unlikely  the main class (-PmainClass=${selected-class})  there isn't any property to pass to the build that will passed over as the arguments for the main class.

I would suggest that all the build in task that use the -PmainClass property check as well for a -PmainClassArgs  parameter and if it is present passes it as argument to the main class (the same way you can assign the 'args' property in the standard JavaExec  task)

**Comment by kelemen** [comment]
If such a special place for declaring the argument is useful to you, I would much rather generalize it and let you define all kinds of variables (both in the global settings and the project settings). I wonder if that is something you would consider good.

**Comment by jdevora** [comment]
If there is a generic way to do it.... perfect....

I was just trying to simplify the implementation...  
The UI has a way to set parameters, but for this parameters to get used, you need to modify the build in tasks in each project ....   
I was thinking follow the path lead by 'mainClass'  and just do something like 
if (project.hasProperty('mainClassArgs')){
  args = project.getProperty('mainClassArgs')
}
 in the buildin JavaExec taks...  

or if there isn´t any side effects even use the same name than JavaExec
something along the line of:...
if (project.hasProperty('args')){
  args = project.getProperty('args')
}
  
Where you set  -Pargs=arg1 arg2   in the project properties in Netbeans

**Comment by kelemen** [comment]
I don't think your sample code would work so easily because args is a list and not a string and the logic of splitting is slightly complicated. So, if I add a support for args specifically, I have to add that to the plugin's custom init script (because I will not add this in a way where the default run task added does not recognize the argument).

That said, adding custom values (or even overriding default ones) for replacable variables, seems to be a good idea.

**Comment by david-hall** [comment]
I'm not sure I follow the question exactly, but I have an example of a
build.gradle file that allows specific parameters from "gradlew run -P" to
be passed as arguments to the main class. It might be helpful or it might
be irrelevant if I'm misunderstanding your question, but take a look and
see if it helps.

https://github.com/vorth/vzome-core/blob/master/build.gradle

Look at the task zomicPP around line 342.

Hope this helps.
David

**Comment by kelemen** [comment]
That is just passing a single argument but if I add this, I will add a generic solution which splits the arguments the same way as the shell does.

**Comment by kelemen** [comment]
To add some partial support for this issue, it is now possible to define custom task variables in the project properties. So, you can now add a variable named "mainClassArgs" and use it as "${mainClassArgs}". That said, there is no special support for arguments, currently you have to interpret this argument manually and overwrite the run (and possibly debug) task. However, the *generic_global_defaults* branch also allows you to define a default global value for every project property (unintuitively you have to do this in the project properties at the moment by selecting the *Global defaults* profile.

**Comment by wadechandler** [comment]
Indeed; which we should prefer. If you have a Gradle project, and you can
not make your build system work because you cannot edit the run nor debug
tasks, then someone who controls your processes doesn't properly understand
Gradle; an example is passing system properties which does not happen by
default. Gradle "is" the project file, and the IDE specific files are not.
This is also true for Maven projects btw. You define your Gradle run task
in a generic way to support running your project how you need to do it.
That is what it is for. How would someone using vi run and debug your
project without building the jar files? What about emacs or Sublime?

Wade

**Comment by kelemen** [comment]
I have added some basic support for this to the master branch:

- The default init scripts will now set the "args" property of `run` tasks if the `cmdLineArgs` project property is present.
- The default `run` / `debug` configuration will property initialize the `cmdLineArgs` property.
- The way users are expected to set the command line args is to add line to the custom task variables in the project properties `cmd-line-args=MyArg1 MyArg2 "My Arg with spaces"`.

Even though, the user interface is not very obvious about how to set (and that you can) the command line arguments, I consider this issue closed. If a better UI is needed, please open another issue.
