### ISSUE TITLE
Feature request: Add support for environment variables in G4NB

### ISSUE THREAD

**Issue by XobSod** [kelemen/netbeans-gradle-project#198]
By default, NetBeans lets you to set environment variables for project (Properties ->Actions ->Run project ->Set Properties: Add). Gradle for NetBeans project does not have this functionality.

**Comment by kelemen** [comment]
I'm not sure what do you mean on setting environment variables. Variables for the script, the environment for JavaExec task of run? Does adding "systemProp.myPropery=myValue" to `gradle.properties` solve your problem?

**Comment by XobSod** [comment]
As far I know, gradle.properties is used to configure build process (I might be wrong).
I mean that I need to provide additional environment variables for application that is managed by Gradle plugin, and started by Netbeans. This question (http://stackoverflow.com/questions/11823233/how-to-set-environment-variable-in-netbeans) provides general solution for NetBeans projects.

**Comment by kelemen** [comment]
NetBeans just executes the `run` task defined by your build script (if your build script has none, the plugin adds a reasonable one). Since there is no standard way of configuring the run command from the command line, I did not add such feature (as it would be surprising if it stopped working after adding your own run task).

My advice, is that you should add a `run` task to your build script and configure its environment variables.

**Comment by XobSod** [comment]
Is there a way to see, what is the form of run task generated by plugin (I just want to copy it and add my configuration)? My project does not require this task in build script, as on working environments it is started by additional script. 

Also a note - my opinion. Since plugin already defines its own run task (it it is not already present), I think there should be an option to add to its generation process possibility to set up additional variables. It this task is present, then the environment setup is done by creator of that task, if not, NetBeans plugin should be able to fully configure this environment.

**Comment by kelemen** [comment]
The init script this plugin applies is [nb-init-script.gradle](https://github.com/kelemen/netbeans-gradle-project/blob/master/netbeans-gradle-plugin/src/main/resources/org/netbeans/gradle/project/resources/nb-init-script.gradle). It is a lot more complex than what you need because it must not throw an error for any build script.

Actually, this is what it does:

    def definedMainClass = project.hasProperty('mainClass') ? project.mainClass : ''
    if (definedMainClass == null) definedMainClass = '';
    definedMainClass = definedMainClass.toString()

    task ('run', dependsOn: project.classes, type: JavaExec) {
        main = definedMainClass
        classpath = project.sourceSets.main.runtimeClasspath
        standardInput = System.in
    }

I'm not sure if I completely understand your comment but what you can do know is to create additional "profiles" in the project properties and have different configurations for the "run" command for each profile.

**Comment by XobSod** [comment]
OK, thank you very much for this information. I'll try to work with that.

**Comment by fwelland** [comment]
not really the same as the OP but some support for Env Vars would be a nice addition...   Here is my use case:     take built-in task  Test Single.  its task are defined as:

${project}:clean${test-task-name-capital} ${project}:${test-task-name} 

I'd like it to be 

${project}:clean${test-task-name-capital} ${project}:#{DRIVER}${test-task-name}
 
where #{DRIVER} is the val of the env var.  

I can easily change it/hardcode it to:

${project}:clean${test-task-name-capital} ${project}:firefox${test-task-name}

to match the value -- works as expected.    However when I change env var "DRIVER" to chrome, I just need to remember to hack the built-in.   That is easy to forget.

Why? oh I am using spock/geb/selinium for acceptance tests and my gradle files use the environment var to select the browser(s) web driver uses to run test.   The corresponding gradle hunk makes a prefixed acceptance test task per browser (listed in env var) -- G4NB is fine and totally sees these tasks and I can pick them out and execute them etc...  While I am authoring a an acceptance test it is convenient to do CTRL-f6.   This will run "acceptanceTest" as planed with -DacceptanceTest.single=.....   but gradle will run all the tests in this case not just the single specified (same on gradle cli).     when I hack in the prefix value 'firefox' like so:

firefoxacceptanceTest -DfirefoxacceptanceTest.single=.....

works just like I want.  

Makes sense?

(maybe I can tinker in gradle to make 'acceptanceTest' work directly -- however I am reluctant because in our pipeline we actually do run our acceptance test thru multiple browsers and we avoid having different build stuff for workstations than from pipeline.  )

**Comment by kelemen** [comment]
Makes sense but instead of the new # notation, it is simplier to stay with the current variable format, say: ${env.DRIVER}. In this form, implementing this feature is trivial.

**Comment by kelemen** [comment]
Bye the way, I think it would be simplier for you to create different profiles with different task configuration because, this way, you can quickly change between browsers (it is easier than changing the environment variable).

**Comment by fwelland** [comment]
yeah -- #{DRIVER} just for discussion purposes -- whatever makes it easy or sensible...

So never really tinkered with the configuration stuff -- I will have to try it out.   Thanks for the tip.

**Comment by kelemen** [comment]
@fwelland I have added this environment var thing (in the form of ${env.DRIVER}) to master, so might build the plugin from the sources if you need it. Though, I think profiles are better for your problem.

**Comment by fwelland** [comment]
Worked like a champ!    So I did both:  I made profile in G4NB called "Use Env Vars" and made test single look like: 

tasks: 
${project}:clean${test-task-name-capital} ${project}:${env.DRIVERS_FOR_ACCEPTANCE_TEST}${test-task-name} 

arguments:   
-D${env.DRIVERS_FOR_ACCEPTANCE_TEST}${test-task-name}.single=${test-file-path}


Worked exactly as you expected.    

THANKS!!!!!
