### ISSUE TITLE
Dependencies with multiple source sets in a multi-project

### ISSUE THREAD

**Issue by swltr** [kelemen/netbeans-gradle-project#199]
Hi,

in a multi-project's subproject, I'm trying to split the Java code of an application into multiple source sets to separate the application logic from its Guice configuration. This is fairly straightforward:

    sourceSets {
      appconfig
    }
    
    configurations {
      appconfigCompile.extendsFrom compile
    }

In NetBeans, this correctly adds a subtree labelled "Compile for appconfig" to the "Dependencies" folder of the project.

As the application's classes need to be on the Guice configuration's classpath, I add the following dependency:

    dependencies {
      appconfigCompile sourceSets.main.output
    }

Surprisingly, this makes the "Compile for appconfig" depencies subtree disappear in NetBeans. I mention this because it possibly indicates the root of the problem described below.

To include the Guice classes in the resulting artifact as a usable default configuration, I also added:

    jar {
      from sourceSets.appconfig.output
    }

This all works with Gradle itself, i.e. it successfully compiles and the Guice configuration is included in the JAR file. Other subprojects in the same multi-project can also reference the Guice classes if they specify a dependency on this subproject. In NetBeans, however, the Guice classes don't seem to be on the other subprojects' classpath. (They are marked with "cannot find symbol" errors of the Java compiler and are not available for auto-completion.)

Can you confirm that there is a problem with handling the dependency of a configuration (`appconfigCompile`) on the output of a different source set in the same project (`sourceSets.main.output`)? If I am doing something I shouldn't do here, please let me know.

I am using NetBeans 8.0.2 with the "Gradle Support" plugin 1.3.4.

Best regards,
Stefan

**Comment by kelemen** [comment]
The dependency node is used for informational puposes only (internally, it is not used for anything at all). The reason why it disappears because since you added `main.output`, it assumes that `appconfigCompile` depends on `compile`, so omits the dependencies found in `compile` and since there is nothing else in it, the node is simply pruned.

As for the actual problem. By default the plugin assumes that `jar` is created from `sourceSets.main` (as far as I know, there is no way for the plugin to figure out what exactly). I already have fix for this in the current master branch where you can explicitly specify the source sets the jar task is created from by writing: `jar.ext.netBeansSourceSets = [sourceSets.appconfig, sourceSets.main]` (I think `sourceSets.main` can be omitted).

Anyway, if you want to build the plugin from the sources, please ignore the current test errors as there is an issue when using Gradle 2.4-rc-1 (only for tests though).

**Comment by swltr** [comment]
Thank you for your explanation. Since this is for a project with multiple developers and is not an urgent issue, I'll probably wait for the next version of the plugin instead of rolling my own release.

**Comment by kelemen** [comment]
I will consider this fixed, since that's the only thing I think I could have done.
