### ISSUE TITLE
gradle.properties not found

### ISSUE THREAD

**Issue by juergenzimmermann** [kelemen/netbeans-gradle-project#224]
The global gradle.properties can be located in a directory which is specified by the environment variable GRADLE_USER_HOME. However, the Gradle plugin for NB ignores this environment variable, and doesn't show gradle.properties inside the folder "Build scripts".
![gradle-properties](https://cloud.githubusercontent.com/assets/734334/9106784/10018690-3c23-11e5-85a6-f9fe3d18bec0.PNG)
I'll attach a screenshot to illustrate the issue.

**Comment by kelemen** [comment]
It is not just particulary gradle.properties but the whole user dir of Gradle (including init scripts). I have to adjust `GradleFileUtils.getDefaultGradleUserHome` to consider the environment variable. Though there will be some awkwardness in some situation because environment variables are inherited from the starting process.

Anyway, for now you can explicitly specify this directory in the global settings (*Tools/Options/Misc/Gradle/Gradle Installation/Gradle user home directory*).
