### ISSUE TITLE
How do you attach source code to dependency jars ...

### ISSUE THREAD

**Issue by hrstoyanov** [kelemen/netbeans-gradle-project#239]
... for debugging? I am looking for the equivalent of this in Maven projects:
https://dzone.com/articles/getting-sources-maven-reposito

**Comment by kelemen** [comment]
You can click "download sources" on the dependencies node and that should work.

**Comment by hrstoyanov** [comment]
Yes, that is exactly what did not work for me ... Not sure why.

/Hristo Stoyanov

**Comment by mfuerstenau** [comment]
This only works **on the parent node labeled _Dependencies_**. Is this supposed to work only on the parent node? Most of the time you don't need all sources.

**Comment by kelemen** [comment]
@hrstoyanov There are two reasons I can think of: One is that the `idea` plugin is configured not to download sources (since this plugin only asks Gradle for the Idea model and assumes that Gradle downloaded the sources). The second is simply that the sources are not available in the repo where the dependency was donwloaded from. The most reasonable cause I can think of is that you have listed `mavenLocal` in the repository list.

@mfuerstenau The problem with individual dependency download is that I cannot tell from `sourceSets.main.compileClasspath` where the individual jars came from.

**Comment by hrstoyanov** [comment]
Attila,
I do not have idea plugin, should I add one?

/Hristo Stoyanov

**Comment by kelemen** [comment]
No, if you don't have the idea plugin applied, it should be fine. So, my best guess is that the dependency is being downloaded from a repository which does not contain the sources of the dependencies you are looking for. As I said, the most common problem is adding `mavenLocal` as a repository.
