### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by marccollin** [kelemen/netbeans-gradle-project#254]
I see some gradle script who use 

apply plugin: 'eclipse'
apply plugin: 'idea'

Don't seem to exist for netbeans.

Is it usefull to use one of them?

**Comment by kelemen** [comment]
For IntelliJ and Eclipse there are two ways how you can use NetBeans. The original way was (and this is still used by some projects) to generate the respective project files. If you do this, you can explicitly alter the generated project files from the build script (tweak the resulting xml files).

The other way is what is used by their respective plugins is that they load a so called "model" of your project in the approriate format (there is an [Eclipse model](https://docs.gradle.org/current/groovydoc/org/gradle/tooling/model/eclipse/EclipseProject.html) and an [Idea model](https://docs.gradle.org/current/groovydoc/org/gradle/tooling/model/idea/IdeaProject.html)). In this case you can use those plugins to adjust these models (in most cases, you want to fix the class path in the model).

Historically, NetBeans used the Idea model (you can still configure it to use that in the global settings). However, since Gradle 1.8 (although Gradle 1.8 itself has a bug which prevents it from being usable in NetBeans) the NetBeans plugin uses the actual class path of the source sets. So, in almost all cases, you don't need to alter anything for NetBeans. Though you can, if you want to (I did so in the past to display some random directories as source set). You have to add code with the following condition:

    if (project.hasProperty('evaluatingIDE') && project.property('evaluatingIDE') == 'NetBeans') {
        // Tweak the build script for NetBeans
    }

There is one thing however for which NetBeans still uses the Idea plugin: Downloading sources of dependencies. That is, the Idea plugin allows you to enable and disable sources and javadoc downloading. This affects NetBeans, if you disable source downloading in the Idea plugin, NetBeans won't download the sources of the dependencies. Similarly, if you enable the javadoc downloading, NetBeans will download the javadoc as well when you request it to download the sources. The default configuration is that source downloading is enabled and javadoc downloading is disabled. If that's good for you, then you don't have to apply the Idea plugin.

**Comment by marccollin** [comment]
ok thanks for theses informations.
