### ISSUE TITLE
Symbol not found errors reported in source

### ISSUE THREAD

**Issue by pron** [kelemen/netbeans-gradle-project#255]
Hi.
I'm using plugin 1.3.8.1 with NetBeans 8.1 and Gradle 2.10. When opening [this project](https://github.com/puniverse/quasar) I get multiple errors reported in the source files (cannot find symbol, package doesn't exist), but they are not reported in the project tree, and the project builds fine (both from the IDE as well as the command line). The project does use a non-trivial source-set scheme, but it has worked fine with the Gradle plugin in the past.

**Comment by kelemen** [comment]
Can you be more specific? For example, can you give me an example class?

**Comment by pron** [comment]
After about an hour or so of the IDE being open, the errors disappeared... I did open other projects, though. That might have had something to do with it. Mysterious....

**Comment by kelemen** [comment]
The main problem with the project (from the plugin's point of view) is that not all subprojects have a *build.gradle* and this seems to cause some anomalies. I'll look into this a little more because things don't seem to work as intended.

My assumption is that this is waht happened for you: NetBeans first determined that *quasar-core* is not a project, so then tried to ask the root project for the classpath. Eventually later however, it forgot (probably due to some weak references getting collected) that it is not a project, so requeried the owned project which at that point could provide the correct class path.

**Comment by kelemen** [comment]
I made some fixes which might help with a project like that. However, not having a build.gradle for a subproject is not officially supported (even though I try to make it as usable as it is reasonably possible).

**Comment by pron** [comment]
Thank you! Would an empty build file (as in a completely empty file) suffice (even though the sub-projects are explicitly mentioned in the root project's build file)?

**Comment by JustGregory** [comment]
@pron
I have many subprojects whose only ```build.gradle``` body is:
```
dependencies {
}
```
and it works as expected. Works the best for Gradle subprojects which are meant to be libraries of classes, used in other classes....

**Comment by kelemen** [comment]
You don't need to have anything in the *build.gradle*. Its mere presence is what is needed only (it might as well be empty).

**Comment by pron** [comment]
Thank you. I'll try that.

**Comment by kelemen** [comment]
In fact, if you don't want Gradle to load those build files, you might create a .gradle with its parent directory name. For example, *quasar-core.gradle* in the *quasar-core* directory.

**Comment by pron** [comment]
Oh, nice tip! I didn't know that. But now I'm curious: if all you need is an empty file -- which even Gradle ignores --  why not just pretend it's there and work without it?

**Comment by kelemen** [comment]
The problem is that NetBeans asks questions like "Is this directory a project directory?". And it does so without a project being opened (this is necessary because you might open files of a project without opening a project). So, I have to have a way to determine if a directory is a project directory or not without actually trying to load Gradle projects (as trying to do so for every directory would be extremly inefficient).

That said, - in theory - once you have a project opened, missing build.gradle files shouldn't be the problem. The theory breaks if something caches a wrong file to project association (created before opening a project).

**Comment by pron** [comment]
OK, I think I sort of get it...
Terrific plugin, BTW. Beats all other IDEs' Gradle support. Thank you for building and maintaining it!
