### ISSUE TITLE
How to debug junit test in custom sourceSet

### ISSUE THREAD

**Issue by farrukhnajmi** [kelemen/netbeans-gradle-project#262]
Thanks for an awesome plugin.

I have gradleized a legacy ant project where I need to keep src files in their current location that does not follow gradle conventions. I have handled this need using a custom sourceSet and configuration.
I need to debug a single test from its non-standard location.

The normal "test" task runs new tests under the normal ./src/test/java sourceSet.
A new "testLegacy" task run the older test under the custom ./test/ sourceSet

If I open the com.test program in the editor and do Debug / Debug Test File the task run is the normal "test" task

Executing: gradle :myproject:cleanTest :myproject:test
Arguments: [-Dtest.single=com/mypackage/TestMyClass, -Dtest.debug, -c, ...\settings.gradle]

And I get the error:

Execution failed for task ':myproduct:test'.
> Could not find matching test for pattern: com/mypackage/TestMyClass

So I created a custom task with following in nb-gradle.properties:

    <task>
      <display-name>Debug Test Single (Legacy)</display-name>
      <non-blocking>no</non-blocking>
      <task-names>
        <name must-exist="yes">testLegacy</name>
      </task-names>
      <task-args>
        <arg>-DttestLegacy.single=${test-file-path}</arg>
        <arg>-DtestLegacy.debug</arg>
      </task-args>
    </task>

Now when I click in the editor window for com/mypackage/TestMyClass and run the custom task it put up a dialog asking me to "Specify task variable" test-file-path.

How doe the normal Debug / Debug Test File built in task have access to this variable and how can I do same for my custom task?

**Comment by kelemen** [comment]
This won't work as a "Custom Task". This is because there is some special treatment for debugging (setting up the debugger) and the plugin only does this for certain actions in NB (obviously, the debugging ones).

However, what you want is doable with the default configuration assuming your test tasks are named "appropriately". Appropriate means that NB will try to guess the name of the test task associated with a given source set based on its name. What it expects is the "usual" naming convention: If your source set is called `legacy`, then the test task name is expected to start with `legacy`. I have just looked at the logic and certainly, there is room for improvement but this how it is done now.
