### ISSUE TITLE
How to stop gradle daemon in netbeans?

### ISSUE THREAD

**Issue by BushNik** [kelemen/netbeans-gradle-project#269]
As title says, how to stop gradle daemon in netbeans? I found [this](https://github.com/kelemen/netbeans-gradle-project/issues/64) but there is no instruction how to do it.

**Comment by kelemen** [comment]
There is no way to stop it from the IDE at the moment because Gradle provides no way to do this through its API. (also running *gradle --stop* doesn't always seem to work for me).

Personally, I'm killing the daemon process. Otherwise, an ugly way to stop the daemon is to start any kind of Gradle task and cancel it from NB. That should stop the daemon running that task.

**Comment by KorvinGump** [comment]
So, how i can kill daemon process? I am starting gradle task, cancelling it, but it continues executing... Also my tasks are very fast, how i can execute 10 second task and kill it?

**Comment by FibreFoX** [comment]
@kelemen this should be mentioned below the "Current Limitations"-section

About stopping/killing the daemon-process [is discussed in the gradle-forum recently](https://discuss.gradle.org/t/stopping-gradle-daemon-via-tooling-api/16004), and there seems to be some [still unresolved issue too](https://issues.gradle.org/browse/GRADLE-1594). Maybe the mentioned workaround/hack with that "killAll"-method could work out here.

**Comment by kelemen** [comment]
@KorvinGump I simply kill the java process manually. Sure, trying to cancel a task is not really a reasonable solution just wanted to mention that cancellation has this affect (however, you need Gradle 2.1 or later for cancellation to work).

@FibreFoX  I don't count this as a limitation (if I did, I might as well do it for any feature request) because it does not affect loading of the project model. Anyway, you don't usually need to stop the daemon.

I have looked at the hack there but it seems to be an extremely dirty hack, so I prefer not to implement it. Especially, since I'd prefer creating a daemon manager dialog instead than simply providing a "kill all daemon" command with no feedback.

**Comment by FibreFoX** [comment]
@kelemen Yes, thats a workaround for the existing limitation of having no daemon-manager or something like it. ;)

I really don't know anything about this plugin, but as far as I understood, this plugin launches gradle in daemon mode, isn't it? Would it be possible to not launch it in daemon mode?

**Comment by kelemen** [comment]
I'm using the Tooling API of Gradle which hides spawning of Gradle processes. There is an embedded mode (internal API) but if I remember correctly that has some limitations (though I can't remember what it was, I can only remember that I decided not to allow that :)).

**Comment by FibreFoX** [comment]
Yes, I read about that embedded mode, but it seems not very attractive of the makers, there are some JIRA-issues still open, like thas: https://issues.gradle.org/browse/GRADLE-2696
While searching, I found this discussion: http://gradle.1045684.n5.nabble.com/Tooling-API-stop-daemon-td4375065.html

> In the meantime, a workaround you can use is to switch the tooling API to 'embedded' mode, via an internal API. This will run the build in the test jvm, rather than using the daemon:
>
> DefaultGradleConnector connector = (DefaultGradleConnector) GradleConnector.newConnector();
> connector.embedded(true);
