### ISSUE TITLE
File tab enahnacements

### ISSUE THREAD

**Issue by hrstoyanov** [kelemen/netbeans-gradle-project#279]
When you open **build.gradle** file this plug-in (or Netbeans?) decorates the file tab with the project name, for example:  **build.gradle[xxxx]**. Can we do the same for other ambiguous Gradle files such as **settings.gradle** and  **gradle.properties**. This would make work with multiple Gradle projects easier in Netbeans, where the tabs can become confusing.

**Comment by kelemen** [comment]
Sorry for the delayed response. For *settings.gradle*, it is possible (and is very simple) by adjusting [GradleDataObject](https://github.com/kelemen/netbeans-gradle-project/blob/v1.3.8.1/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/filesupport/GradleDataObject.java) appropriately. As for *gradle.properties*, I'm not sure because that file type (properties) is not managed by this plugin.

**Comment by hrstoyanov** [comment]
Thanks,
Whatever can be done will help. My open tabs right now are a mess ...

**Comment by kelemen** [comment]
The settings.gradle annotation is now in master.

**Comment by hrstoyanov** [comment]
Thank you!

**Comment by kelemen** [comment]
Thanks to @markiewb, I have added annotations for *gradle.properties* as well. However, there is a caveat: It only works if you have *Tools/Options/Appearance/Multi-row tabs* selected. If you want to, you can build the *gradle_properties_tab_decorator* which contains these changes.

**Comment by hrstoyanov** [comment]
Yes, I always use 3 rows for tabs.  Waiting for the next release of this life saving plugin! Thanks!

**Comment by kelemen** [comment]
Ok, I'm not sure when I will build a next release but until then, you can build the plugin yourself (if you do it for only yourself, it will build out-of-the-box). If you want to build it properly, you can refer to the [Development page](https://github.com/kelemen/netbeans-gradle-project/wiki/Development) of the wiki.
