### ISSUE TITLE
Gradle plugin for Netbeans 8.2?

### ISSUE THREAD

**Issue by hrstoyanov** [kelemen/netbeans-gradle-project#292]
Netbeans 8.2 was released today...

**Comment by kelemen** [comment]
Yes, I was waiting for something to have a new release but I guess, I won't do so any longer.

**Comment by kelemen** [comment]
By the way, does NB 8.2 works fine for you? Because if I try to open this plugin in it: Red curlies are all around the place (all related to generics). Also, for now you can use the latest release (or build the plugin from master).

**Comment by hrstoyanov** [comment]
When I installed NB 8.2  and went to available plugins, this plug-in did not show, so I switched back to 8.1

**Comment by wadechandler** [comment]
I installed from the 8.1 update center into 8.2 actually, and all my Gradle projects which I have opened are working as expected.

**Comment by kelemen** [comment]
Currently, these are the two issues I know of:

- https://netbeans.org/bugzilla/show_bug.cgi?id=268334 (I don't think this plugin has anything to do with it)
- https://netbeans.org/bugzilla/show_bug.cgi?id=267789 This might be because of this plugin but I cannot reproduce it, so I'm not sure (I made some adjustment which might solve this issue).

That said, you should be able to install the plugin for NB 8.1 into 8.2. Though, if you want to wait, I plan to have a release this week, I just need to create the release notes and adjust the wiki, since there are quite a few changes in the settings UI.

**Comment by hrstoyanov** [comment]
@kelemen 
I can wait. I know you packed more changes and features in the new release. Your work is very much appreciated by the Netbeans community!

**Comment by kelemen** [comment]
The plugin portal of NetBeans won't let me upload the plugin. It says: "Your plugin seems to contain SPAM data!". I will ask around what this issue can be and how to resolve it. @wadechandler Do you know anything about this?

**Comment by kelemen** [comment]
Even more strange: It lets me upload it for NB 8.2 but not for 8.1. So, the plugin is now uploaded for NetBeans 8.2, and I will update it for 8.1 as well later.
