### ISSUE TITLE
test.single and ${project.path} and something busted? 

### ISSUE THREAD

**Issue by fwelland** [kelemen/netbeans-gradle-project#293]
Hi, 

Firstly -- thanks for your work!

So I am on 8.2 and G4NB 1.3.9   (linux and jdk 8. blah blah).    When I installed nb 8.2 (like on tues or wed of this week)  -- I had it import my old plugins.    And then I had to re-install groovy-grails plugin and then G4NB worked.      (I just updated to 1.3.9, a few hours ago). 

test.single is running all of test not just the test I have in editor window.   (was using g4nb 1.3.8.1 recently and this worked just fine  --  sorry I do know know if NB 8.2 + G4NB 1.3.8.1 had working test.single or not I only had that combination for about 24 hours (before G4NB 1.3.9) and I was working on other things...)
   
The output in the window (while running test.single)  is
````
Executing: gradle :cleanTest :test
Arguments: [-D::test.single=fhw/model/RateCardSpecification303, -c, /home/fwelland/JavaStuff/NetBeansProjects/GettyUpServices/settings.gradle]
````
The double '::' seems at fault.   

The task defined in project ->properties->builtin tasks->Test Single is marked 'inherit' and it looks like:  
tasks:
````
${project}:clean${test-task-name-capital} ${project}:${test-task-name} 
````
arguments:
````
-D${project-path}:${test-task-name}.single=${test-file-path}
`````

It almost looks like $(project-path} has some extra ':' prepended to it?      I am using the default profile. 

Could I have changed what ${project-path} is?    If so can I change back?

**Comment by kelemen** [comment]
I can reproduce this issue. And it only fails for the root project (I assume you have single project build). However, it seems there is no trivial fix because using a single ":" won't work as well. The `${project-path}:` prefix was introduced to fix #287, so I cannot just remove the prefix.

The current workaround you can do is to adjust the "Test Single" (and probably the Debug Test Single as well) built-in task:

- Adjust the tasks line to: `${project}:clean${test-task-name-capital} ${project}:${test-task-name} --tests ${selected-class}`
- Remove the line containing `... .single=${test-file-path}` from the arguments.

You can now do this for the newly added `<Global defaults>` profile as well, so you don't have to do this for all projects. This workaround won't work for Gradle versions before 2.3, if that is what you need, you can just remove `${project-path}:` from the previously mentioned task definitions.

**Comment by fwelland** [comment]
correct, single root gradle.   

Note:  I do lots of toys that are a single root project; but my real work is in a larger multi-sub gradle project.     

I'll deploy one of the tweaks you suggest  (I'll provide feed back if something doesn't work) 

You can close/manage this issue as you see fit --  I am 100% confident that you'll tend to this issue is some forth coming work.   

Thanks a bunch for your work!!!!!

**Comment by kelemen** [comment]
My current idea is to switch between how the test class is selected based on the version of Gradle used to load the project. It is not 100% because what you have used to load the project might not be the same as what you will use to execute the task but is a reasonable bet.

**Comment by kelemen** [comment]
I have adjusted the test single and debug test single tasks to use the "--tests" way when Gradle 2.3 or later was used to load the project. You can try building the "master" branch and use that until a new release.

**Comment by fwelland** [comment]
Thanks!

I will give it a go.

**Comment by fortiernor** [comment]
I've applied the fix you suggest, this solves the issue (thank you!) so that only the selected file is tested; I've applied it also to the debug test file task (same task definition as test single, remove first argument).
However in both cases (test single and debug test single) each test method is executed twice.

**Comment by kelemen** [comment]
@fortiernor The double execution seems very strange and I doubt that it is caused by this plugin because the plugin just runs the test task. The reason I can think of is that you have two test tasks (for the same source) and test depends on one of them.

**Comment by fortiernor** [comment]
Indeed if I write a very simple test class with one test method, it gets executed once. Thanks.
