### ISSUE TITLE
JPA project not working correctly

### ISSUE THREAD

**Issue by ferreirajoao** [kelemen/netbeans-gradle-project#302]
Hi,

I have migrated my JPA EclipseLink project in Netbeans to a Gradle project.

However the wizards in File > New file are missing some options (see screenshots below)

Before mirating to Gradle:
![pre_gradle](https://cloud.githubusercontent.com/assets/15709065/19951830/86464944-a158-11e6-8c0c-a6ab66c67b66.png)
 
After migrating to Gradle:
![gradle](https://cloud.githubusercontent.com/assets/15709065/19951831/88aef3a2-a158-11e6-9e7c-6b1e2a02094b.png)

Also if I drill down to the location of the persistence.xml file the option to "Run JPQL Query" is unselected and I cannot use it anymore.
![jpql](https://cloud.githubusercontent.com/assets/15709065/19952001/b322ea3e-a159-11e6-8eee-d719e254572d.png)

I don't know if this project type is not supported yet, or am I missing some configs.

Please advise. Thank you.

**Comment by bhorn** [comment]
+1
Can't add Entity-Classes or edit the xml via GUI.

**Comment by kelemen** [comment]
JPA support should be provided by the [Gradle EE plugin](https://github.com/hildo/netbeans-gradle-javaee-project) and not this plugin. If you have the EE plugin installed and you still have the issue, please report it there.

**Comment by bhorn** [comment]
@kelemen **Report** :(
Installed EE Plugin, restarted Netbeans.
Still unable to edit the xml or add Entity-Classes.

**Comment by fwelland** [comment]
I bumped into a the same or similar problem a while back.    I think I brought it up with the NB guys -- but I can't find the bugzilla on it.     But maybe I brought it up here -- don't recall.   

In short there is a handful things, wizards and code generators, some plugins, that do not work with gradle projects.    

I think the NB peeps feel  it is on the plugin author and perhaps plugin authors feel the other way.    

My take is that if G4NB faithfully implements a project plugin -- then it should have access to all the stuff that other project types get (whom also faithfully implement the project plugin interface.  NOTE:  I am taking a leap that there is a specific project plugin interface other than just the NB plugin interface).  

It maybe that other project types,  that have support for these things, may not really be project plugins, but just intrinsic features of NB.   So that those these wizards and features just 'know' about the project types.     Purely speculation, on my part....

Having said that,   I use G4NB lots  along with the G4NB EE plugin.    Often the 'fancy' UI comes up when I open a persistence.xml file.      However, never gotten the add entity-classes to work ( I stopped tring long time ago...)

**Comment by ferreirajoao** [comment]
Thank you for your answer @kelemen. However as @bhorn mentioned adding the [Gradle EE plugin ](https://github.com/hildo/netbeans-gradle-javaee-project )did't make a difference.

**Comment by kelemen** [comment]
@fwelland There is no NB plugin interface but there is plugin interface (so to say) what this plugin implements in [NbGradleProjectFactory](https://github.com/kelemen/netbeans-gradle-project/blob/51acfe042cbc06290c2ca1a6b8a5453239b45b23/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/NbGradleProjectFactory.java). However, it is not as simple as you would think. There is no common reason why features do not work.

- The simplest is that some NB features do not explicitly list the name of this plugin (this is the easiest fix but can only be done in NB).
- There are cases where NB simply does not open its API for this plugin (or the EE plugin), this issue can be worked around with a hack though.
- Most of the times however, features simply do not work because the plugin provides no support for them (NB usually needs some information from the project to allow them).

Usually, not implementing them is difficult but to find what to implement and to find out what the required interface means for NB (i.e., what info do you need to provide). Also, you have to consider all kinds of hidden implications of implementing those queries. As much as I know, the only way to figure these things out is to reverse engineer other project types (and this is not so trivial given that the provided interfaces are scattered all around in different projects). As for EE stuff, I didn't implement it because it takes so much time and I personally have no need for it, so I guessed (hoped) that someone motivated to have the feature will implement those queries. Back then Hildo started doing so but (given the low activity) I guess he does not have as much time as he has hoped.

So, if you are feeling adventurous, you might try to add these things yourself. Though expect to do a lot of research if you choose so. Regardless, I can (and will) help you using the API of this plugin and whatever I can but I don't have the time to pick up the EE support as well (also, since I would not use it, it would be hard for me to decide if support added is good/enough or not).

**Comment by JustGregory** [comment]
<strike>Is it the case where the NetBeans team has made it so independent plugin developers can make their plugins, but maybe not provided a system where other plugin developer can register to use parts or all of others' plugins for consumption?</strike>

I was just writing something along the lines of what @kelemen just popped in with; it's been a few years since I was even bold enough to *think* about NetBeans Module plugin development, and I may have been mis-remembering things about inter-module dependencies.

But as I think about it now, whether you "personally have no need for it", could you have an SPI/framework where others could have a simplified manner to add in add in support for such things?

**Comment by kelemen** [comment]
@JustGregory You can use API of other plugins (the Gradle EE plugin is actually using the API of this plugin). And yes, if someone wants to other support for any feature, I will make sure that this plugin provides a reasonable way to do so (I just need to know what is needed exactly).

**Comment by JustGregory** [comment]
I don't have any idea for JavaEE because I've not tried developing that (I would love to someday, just point me to a good starter tutorial because one of my projects might fit); but most of the suggestions I would suggest are along the lines of having access to the "new file types" file creation, similar to what @ferreirajoao experienced. No concrete recommendation list as I type this, other than to suggest if he (Joao) or @kelemen would not mind renaming the issue title to be more inclusive of other "missing" file types and features?

I am not complaining for any of it; overall, I've been _more than happy_ in using NetBeans, Gradle, and the netbeans-gradle-project for several years now, but I *have* had to change my developer-mindset, in switching to this module over an Ant-based project.  As it seems, before using this module I had access to more file types from a plain-Java class-library project, than switching to Gradle usage (shortly after the Minecraft Forge team started ForgeGradle, I assure you) and finding not all things worked the same as before. But I've also seen many improvements and changes since the Gradle 1.2 days, and it's been (usually) good so far. Enough time has passed that I'm not so much frustrated at what I *cannot* do, as happy at what I *can* do. (I don't know if it's just a matter of how the dialog or contextual menu of new file types is displayed different when the project type is this module's versus a default Java classlib, or something else; I'll have to tinker with that some.)

But again, it's just that: Gradle itself is helping developers to think of the development process in a whole new way, whether a developer works in a large team or solo, and this module has helped immensely.

**Comment by kelemen** [comment]
To add to those lists, I believe you have to add the appropriate "recommended template" to [GradleProjectTemplates](https://github.com/kelemen/netbeans-gradle-project/blob/51acfe042cbc06290c2ca1a6b8a5453239b45b23/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/java/query/GradleProjectTemplates.java#L44-L46) though I don't know what string is what exactly. Also, now that I'm checking this, I might need to add a "merger" to allow extensions to add additional entries to the list.

**Comment by bhorn** [comment]
@kelemen 
Thanks for that! I added the needed strings/xml-Files to that lists and now I can implement Entity-Classes and so on. Persistence-XML-GUI is still broken.
I'll create a Pull-Request for this :)
