### ISSUE TITLE
Successful Gradle project - Build fails with exception under Netbeans

### ISSUE THREAD

**Issue by aplatypus** [kelemen/netbeans-gradle-project#326]
The attached script causes an exception when running on Netbeans.  It works to completion when run on the console on Linux.  Don't worry too much about that it does, I am just looking at how to load properties files from a common file -- This is just a wee experiment.

The script it self works on the console and as a groogy script the function works as expected.  All versions seem to match between Netbeans and the Bash session.  So I expect it some parameter or setting I'm not aware of on the Netbeans side of things.

Many thanks.
......

Product Version = NetBeans IDE 8.2 (Build 201609300101)
Operating System = Linux version 4.4.0-66-generic running on amd64
Java; VM; Vendor = 1.8.0_121
Runtime = Java HotSpot(TM) 64-Bit Server VM 25.121-b13
Gradle version: 3.4.1
Groovy version: 2.4.7

STEPS:
  * I am attaching a sample project
  * Run: gradle build on the command line
  * Open same project in Netbeans
  * Run: gradle build  use f11 or menu, etc. in Netbeans

ACTUAL:
  Running gradle build on shell (Bash) console -- SUCCESSFUL

  Runnin within Netbeans context fails with an Exception

EXPECTED:
  BOTH builds should produce the same result

  Netbeans build is not Successful.  It should succeed.

**Attachments**:
 - project example (gz)
 - console bash shell  gradle output
 - Netbeans gradle output 
 - gradle stack trace 

[try-gradle.tar.gz](https://github.com/kelemen/netbeans-gradle-project/files/836348/try-gradle.tar.gz)
[console (Bash) Netbeans Gradle output.txt](https://github.com/kelemen/netbeans-gradle-project/files/836350/console.Bash.Netbeans.Gradle.output.txt)
[Netbeans Gradle output.txt](https://github.com/kelemen/netbeans-gradle-project/files/836351/Netbeans.Gradle.output.txt)
[gradle stack trace.txt](https://github.com/kelemen/netbeans-gradle-project/files/836353/gradle.stack.trace.txt)

**Comment by aplatypus** [comment]
**Update**:
I can definitely tell you what the problem is.  Netbeans is starting the gradle script from the Netbeans User directory and NOT in the project directory as set by:
 - `netbeans --userdir path`

As far as I know every Netbeans project _normally_ starts the build in the project directory.  Before a maven build starts for instance there is a line in output changing the current directory to the project's directory.

I don't know how Netbeans decided it was going to start or use the usedir for context.  May be it is just one of those things.  I've been using different `--userdir` for several years.  This is the first time I ever detected their existence at runtime or during a build.

I added some more diagnostic statements:
```
        println "  loading: '${fileName}' ...";
        println "  loading: '${propFile.getCanonicalPath()}' ...";
        println "";
```

Result:
- Netbeans is running the Gradle build in the Netbeans User folder and Not the project folder.

on bash:
 ```
  loading: 'common.properties' ...
  loading: '/mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle/common.properties' ...
```
in netbeans
```
  loading: 'common.properties' ...
  loading: '/mnt/data/home/william/.netbeans/v08.02/01/common.properties' ...
```
Netbeans user directory is set-up to run `~/.netbeans/v08.02/01`

**Comment by aplatypus** [comment]
**Update 2** ...

I have added a fix to ensure that the Gradle script is actually running in the **project directory**  It got past the wrong directory situation with Netbeans (and the bash shell `gradle build`, still works *fine*).

To ensure Java `userDir` is the  **project directory** or `project.projectDir` a the top of my `build.gradle`.

        println  "Root project:   "+ project.rootProject;
        println  "  rootDir:      "+ project.rootDir;
        println  "  projectDir:   "+ project.projectDir;
        println  "  project dir:  "+ System.getProperty("user.dir");

        System.setProperty( "user.dir", project.projectDir.toString() )   //  <-- FIX
        println  "  project dir:  "+ System.getProperty("user.dir");

The netbeans output for  this patch is:

```
Root project:   root project 'try'
  rootDir:      /mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle
  projectDir:   /mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle
  project dir:  /mnt/data/home/william/.netbeans/v08.02/01
  project dir:  /mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle
```

This hasn't fixed my _actual_ problem but it has ensured that I'm using the correct file and location.  In the property load bit it now prints:

```
  ~~  ~~  ~~
  loading: 'common.properties' ...
  loading: '/mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle/common.properties' ...
```

So NOW the `properties.load()` method is looking at the correct file.  Witnessed by:
```
$ #  Pasted in the name from Netbeans output
$  cat /mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle/common.properties
########    ########    ########    ########
##
##      global common properties
##
##  file:   common.properties
##
########    ########    ########    ########
#
#           variables
#
#
    zzz             = zzz
    ext.zzz         = ext.zzz

    ext.PAD_INC     = ....
    ext.pad         = pad
$
```

And, yet, Netbeans is still telling me ...
```
* Where:
Build file '/mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle/build.gradle' line: 128

* What went wrong:
A problem occurred evaluating root project 'try'.
> common.properties (No such file or directory)
```
the stacktrace agrees with:  **`FileNotFoundException`**  
```
Caused by: java.io.FileNotFoundException: common.properties (No such file or directory)
	at build_4bkt2fsvr8pjrqay9oxd7wgg6.loadProperties(/mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle/build.gradle:128)
	at build_4bkt2fsvr8pjrqay9oxd7wgg6.run(/mnt/data/home/projects/sandbox/lab/gradle-lab/try-gradle/build.gradle:50)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 70 more
```
It is a little weird.  The command line `gradle build`, works every time.  The file Does Exist.  The path and name are (_now_) but the "_File_ (is) _Not Found_"

**Comment by kelemen** [comment]
That NB sets the working directory for other build types is nice but not very relevant in case of Gradle. This is because in Gradle you have the so called Gradle daemon and using it simply makes it impossible to set the working directory for a Gradle build.

It might be a reasonable feature to be able to configure NB to use a command line version of Gradle. However, it is very low priority because you shouldn't really do that anyway. The reason why you should not do that is because not using the daemon slows down the build by a lot.

Therefore, I strongly recommend not to rely on the current working directory in a build script. In fact, I have never ever met a problem (for build scripts) where relying on the working directory is needed (or would really simplify anything). Therefore, I argue that if a build script relies on the working directory, the build script is broken and needs to be fixed. If you don't do that, your build will fail when using the Gradle daemon (and since Gradle 3.0, the daemon is enabled by default) even from the command line.

Also, the "correct" solution is very simple:

- Use `file('MyFile.txt')` instead of `new File('MyFile.txt')` when you are in a Gradle script (`file` is the method of `org.gradle.api.Project`).
- If you are in a utility method of some sort (or anywhere not in a script), you must take the project directory you must resolve your path against (which is available in the script via the project property `projectDir`).

Also, I would not recommend your hack because it can fail to work unexpectedly (in some situation) if someone has cached the working directory prior to executing your build script.

**Comment by aplatypus** [comment]
I disagree.  It seems there is a diffence in semantics between Netbeans and the Gradle documents.
I'm placing follow-up comments in issue #159 to avoid cross-posts.
