### ISSUE TITLE
Cannot open Gradle 3.5 project, no indication why not

### ISSUE THREAD

**Issue by rdiez** [kelemen/netbeans-gradle-project#336]
This repository upgraded recently to Gradle 3.5, and I cannot open it anymore:

https://github.com/mucommander/mucommander

I guess this version of Gradle is too new for the plug-in. The trouble is, I cannot find which Gradle versions are supported. This is probably worth documenting. It would also be better if the plug-in would recognise the directory as a Gradle project, and then issued an error message stating that it is too new for the plug-in.

**Comment by kelemen** [comment]
I can open that project without any problem with Gradle 3.5 (and can also do other projects with 3.5). Can you specify what exactly your problem is?

If the plugin does not work (fully) with a particular version of Gradle, it will report it when you attempt to use it. So far, there is only two unsupported version: 1.8 (breaks debugging) and 2.3 (partially supported).

**Comment by rdiez** [comment]
Sorry, my mistake, the plug in was installed but disabled.
