### ISSUE TITLE
Missing a hotkey to "Reload Project", not listed in "Keymap" "Actions"

### ISSUE THREAD

**Issue by birgersp** [kelemen/netbeans-gradle-project#340]
Hi,

I've just started using Gradle. I keep having to reload the project by right-clicking the project, then selecting "Reload Project". I'd really prefer to use my keyboard to do this, but I can't assign a key to that action, because I cannot find the "Reload Project" aciton in the list of actions in the "Keymap".

Suggestion: Implement a hotkey to trigger "Reload Project".

**Comment by kelemen** [comment]
I wanted to do this a long time ago just forgot about it. I will look into how hotkeys can be registered with the NB API.

**Comment by kelemen** [comment]
This should now be fixed in master. You can find the action in the *Keymap* by the name "Reload Gradle Project" under the category "Project". I don't want to annoy people with an update for such a small thing, so until next release, you should build the plugin from the sources (it should build out of the box) and install the built nbm manually.

**Comment by birgersp** [comment]
Such a quick response and reaction, thanks a lot @kelemen !
