### ISSUE TITLE
Failing to load projects that are missing settings.gradle

### ISSUE THREAD

**Issue by birgersp** [kelemen/netbeans-gradle-project#351]
Projects missing a `settings.gradle` file fail to load without a "Project Problem". Is this file really necessary? I can build gradle projects from the command line just fine without this file. The file doesn't actually need anything in it, it just needs to be present for the project to load with the "problem"...

I suggest that projects should be loaded without warning/error even if the settings.gradle file is missing.

**Comment by kelemen** [comment]
They should load, unless another settings.gradle is mistakenly believed to be its settings.gradle. What does it mean that "without a Project Problem"? Can you describe exactly what happens?

Anyway, altough settings.gradle is not necessary, I would recommend it anyway because it explicitly defines the root directory and prevents Gradle from searching the parent directories for one.

**Comment by JustGregory** [comment]
@birgersp I think that in this case, adding a blank ```settings.gradle``` file would do the trick. You are right in that it *probably* doesn't need the file in most cases, ... but it's such a minor issue that's easily solvable, so why even hesitate to add it?

**Comment by kelemen** [comment]
@JustGregory You must never add a settings.gradle to child projects (only the root) because then they become a separate build and its behaviour will depend on from where the you call that project. Since, you do not explicitly load projects in NB (opening it is mostly a display thing), you can also expect strange behaviour in NB if you have multiple settings.gradle in the (supposedly) same build.

**Comment by JustGregory** [comment]
Ah, yes, I stand corrected. Now that I think about it, I should have struck the "and to declare subprojects" from my response before posting -- oh well, I live and I learn. Sorry for my mistype....

**Comment by kelemen** [comment]
No problem, I guess it happens to the most of us :)

**Comment by birgersp** [comment]
I've been trying to reproduce the error, but I can't. I was certain that opening a gradle project with the plugin without a `settings.gradle` would produce an error, but it seems I was wrong. Not sure what initially happened. Sorry.

Thanks for a great plugin!
