### ISSUE TITLE
"nothing to fix in import" -- wrong.  fix imports broken.

### ISSUE THREAD

**Issue by THUFIR** [kelemen/netbeans-gradle-project#363]
I think this is a bug:

https://stackoverflow.com/questions/46873255/netbeans-nothing-to-fix-in-import-statements-yet-import-is-required-gradle

basically, what happens is that from the CLI gradle runs everything fine.  The IDE isn't handling the imports and libraries correctly.  it's not fixing imports, not adding needed imports, reporting that valid libraries on the classpath (?I think?) don't exist, etc.

Again, from the CLI gradle works beautifully.  Just the IDE is reporting non-errors and not picking up on packages.  Hope that makes sense.

**Comment by Hillkorn** [comment]
Can be closed as the project was not reloaded after adding dependencies. Can we add some kind of auto reload like IntelliJ has?

**Comment by kelemen** [comment]
It is possible to add, I have never added that because I personally would find that annoying (of course, it wouldn't hurt as an opt-in feature). Since many people have already asked for it, I will consider adding but I still haven't got around finishing the Java 9 updates for the dev build of NB (so that will surely take priority).
