### ISSUE TITLE
Annotation use displayed as error in Navigator and source browser

### ISSUE THREAD

**Issue by theVigster** [kelemen/netbeans-gradle-project#383]
Annotations display in the UI navigator and source code editor as having compile errors.  This can be tested by using the code posted by cesarizu in issue #1 which looks like it solved this issue.  The code builds without errors (I did update build.gradle to use Lombok version 1.16.20).

**Comment by kelemen** [comment]
I have tried this with a Maven project and it seems the same problem is present there as well. So, I assume this is an NB bug and is not related to this plugin. So, you should probably report it on [NetBeans' issue page](https://issues.apache.org/jira/projects/NETBEANS/issues).

If it turns out that something needs to be fixed in this plugin, please reopen.
