### ISSUE TITLE
Rerun and Rerun Failed operations not available with Netbeans 11 and plugin 2.0.2?

### ISSUE THREAD

**Issue by tcfurrer** [kelemen/netbeans-gradle-project#426]
I'm testing Netbeans 11 vc4 on Windows with Gradle plugin 2.0.2.  The test results pane has the "Rerun" and "Rerun failed" buttons always disabled.  These worked on Netbeans 10.  Can this functionality be restored?

I don't know if this is a project-specific issue or not.  If you aren't seeing the same behavior, I can try to provide a tiny test project where the issue occurs for me.

**Comment by tcfurrer** [comment]
Of the four new issues I filed today, this is one is of relatively lesser importance.

**Comment by kelemen** [comment]
This is very suspcious, because this plugin simply returns *true* for `enabled`. See: https://github.com/kelemen/netbeans-gradle-project/blob/v2.0.2/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/java/test/TestXmlDisplayer.java#L236-L238

Might be a conflict with the new built-in plugin?

**Comment by tcfurrer** [comment]
This issue went away when I uninstalled the "Gradle" and "Groovy and Gradle" plugins, leaving only the "Gradle Support" plugin installed. I didn't realize that it was necessary to actually uninstall those conflicting plugins. I thought the fact that they were "disabled" would be equivalent to them not being installed, and so I didn't think to try uninstalling them. Bad assumption on my part there.
